include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true
    package_api_docs: true
    always_put_required_named_parameters_first: true
    prefer_double_quotes: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_foreach: true
    public_member_api_docs: true
    require_trailing_commas: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    sort_pub_dependencies: true

