name: spice_squad
description: The Flutter App 'SpiceSquad'.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  image_picker: ^1.0.0
  intl: any
  jwt_decoder: ^2.0.1
  mobile_scanner: ^3.3.0
  path_provider: ^2.0.15
  pdf: ^3.10.4
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/ingredientIcons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#00010F"
  adaptive_icon_foreground: "assets/images/logoForeground.png"
  ios: true
  image_path: "assets/images/appIcon.jpg"
