@host = http://localhost:3000

@idToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BpY2VzcXVhZC1mZDMyYSIsImF1ZCI6InNwaWNlc3F1YWQtZmQzMmEiLCJhdXRoX3RpbWUiOjE2ODg4OTYwNzQsInVzZXJfaWQiOiJac2Q5YzR6M3RpVVpibkxGZEJuRFd5RHRCSmcxIiwic3ViIjoiWnNkOWM0ejN0aVVaYm5MRmRCbkRXeUR0QkpnMSIsImlhdCI6MTY4ODg5NjA3NCwiZXhwIjoxNjg4ODk5Njc0LCJlbWFpbCI6ImVycm9yY29kZTQ5MjIwMDJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImVycm9yY29kZTQ5MjIwMDJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.BxIWa6tUSrVglsCoKjcEKwRHoVMH3GtrBgXDtAymED7iGO9o0OBKn3qStb53qZtbsef8dyf9ixnbWaH49qzMVUb_BiOG0sCtDBd43HxjPZ1qKZjBX_qwYNX6cuGavPyWXbWlxqht_sqHKJ95fI2jIrbd7SFbHd0jGwKdHYlplxxdMmBBwK-impCLIr9rK315fKdk1OiQRkkReushhZsYAZOKKcMFuMwPVLGZXo3UIIN99byk1EdjyJBxiTP8BKvAcljpJSnijtcXC_6puzlPUJiObJxbhkbhtGTCC9BmKOyXPoTWXLg-WQ22HUEZYOh2fGqqJrqvLXU7ZGSj-NY1Ug




@refreshToken = APZUo0SDbxrtKbrOhZF_3KKlBy2kwnE9-kHgTNDNstaXpJP91UDiEOKji84uNtuuYouY4l1E5Yb4Dzgr5Hs88G-QluXFMOvO0wjHzYJY0WSDu_e7LgyF3hT8NOIi2gv9ME5XJXxKqPdr2ZvQFsscQjn0KL2FVx8HodqB574CpDw0suisbj_ZGxoHvVMj5ToDBkLThKzqNROfD-y9ct9K4rIhva_TMcbHQg

### Get user via API

POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyACtGR4SgCI8V3iFv2Kc4iUJWhciE4mkgg
Content-Type: application/json--data-binary

{
	"email": "errorcode4922002@gmail.com",
	"password":"",
	"returnSecureToken":true
}

### Register new user
POST {{host}}/auth/register
Content-Type: application/json

{
    "userName": "errorcot",
    "email": "errorcode4922002@gmail.com",
    "password": "arischeZuppe"
}

### Login user
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "errorcode4922002@gmail.com",
    "password": "arischeZuppe"
}

### Reset password
POST {{host}}/auth/resetPassword
Content-Type: application/json

{
    "email": "errorcode4922002@gmail.com"
}

### Refresh token
GET {{host}}/auth/refreshToken
Content-Type: application/json

{
    "refreshToken": "APZUo0SDbxrtKbrOhZF_3KKlBy2kwnE9-kHgTNDNstaXpJP91UDiEOKji84uNtuuYouY4l1E5Yb4Dzgr5Hs88G-QluXFMOvO0wjHzYJY0WSDu_e7LgyF3hT8NOIi2gv9ME5XJXxKqPdr2ZvQFsscQjn0KL2FVx8HodqB574CpDw0suisbj_ZGxoHvVMj5ToDBkLThKzqNROfD-y9ct9K4rIhva_TMcbHQg"
}

### Create Group
POST {{host}}/group
Content-Type: application/json
Authorization: {{idToken}}

{
    "name": "Ravtscheev stinkt"
}

### Delete Group
DELETE {{host}}/group
Content-Type: application/json
Authorization: {{idToken}}

{
    "group_id": "4506dff6-f758-4606-8eb9-a7e3e4b7d0ba"
}
  
### Patch Group
PATCH {{host}}/group
Content-Type: application/json
Authorization: {{idToken}}

{
    "group_id": "4506dff6-f758-4606-8eb9-a7e3e4b7d0ba",
    "name": "Almanküche"
}

### Join group
PATCH {{host}}/group/join
Content-Type: application/json
Authorization: {{idToken}}

    {
        "groupCode": "15XBU8JY"
    }

### Get Groups
GET {{host}}/group
Content-Type: application/json
Authorization: {{idToken}}

### Get Recipes
GET {{host}}/recipe/4f98abae-2d0a-4e6b-8799-39bd184d8de8
Content-Type: application/json
Authorization: {{idToken}}

### Create recipe
POST {{host}}/recipe
Content-Type: application/json
Authorization: {{idToken}}

{
    "title": "Fils de pute",
    "image": "23",
    "duration": "30",
    "difficulty": "easy",
    "ingredients": [
        {
            "name": "Tomato",
            "icon": "08b685d4-f076-4636-ac85-50225468f38c",
            "amount": "2",
            "unit": "pieces"
        },
        {
            "name": "Salt",
            "icon": "08b685d4-f076-4636-ac85-50225468f38c",
            "amount": "1",
            "unit": "teaspoon"
        }
    ],
    "instructions": "8==D",
    "isVegetarian": true,
    "isVegan": false,
    "isGlutenFree": false,
    "isKosher": false,
    "isHalal": false,
    "isPrivate": false,
    "defaultPortions": "2"

}

### Delete recipe
DELETE {{host}}/recipe/a23ae456-8d9a-4748-b6fd-2acd621eaa89
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "7eda6c37-c963-40a9-81c2-72b1382972b8"
}

### Get recipe
GET {{host}}/recipe/29026783-e796-49b8-98b6-d6f198b453f0
Content-Type: application/json
Authorization: {{idToken}}


### Update recipe
Patch {{host}}/recipe/5ad5693e-430b-463a-976d-c3cde4c865ee
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "51f5ce1c-a224-48ba-b643-bd72d965aac9",
    "title": "A updated recipe",
    "image": "21",
    "duration": "40",
    "difficulty": "medium",
    "ingredients": [
        {
            "name": "Tomato",
            "icon_name": "ds",
            "amount": "2",
            "unit": "pieces"
        },
        {
            "name": "Salt",
            "icon_name": "fe",
            "amount": "1",
            "unit": "teaspoon"
        }
    ],
    "instructions": "Lorem impsum dolor sit amet",
    "is_vegetarian": true,
    "is_vegan": false,
    "is_gluten_free": false,
    "is_kosher": false,
    "is_halal": false,
    "is_private": false,
    "default_portions": "2"

}

### Set recipe as favorite
PATCH {{host}}/recipe/setFavorite/51f5ce1c-a224-48ba-b643-bd72d965aac9
Content-Type: application/json
Authorization: {{idToken}}

{
    "is_favorite": false
}

### Censor recipe
PATCH {{host}}/admin/setCensored
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "d955d656-eed1-49f0-a5e9-9d1fb351023a",
    "group_id": "0913092b-efda-493f-8351-74e06d4a28d3"
}

### Make Admin
PATCH {{host}}/admin/makeAdmin
Content-Type: application/json
Authorization: {{idToken}}

{
    "target_id": "4f98abae-2d0a-4e6b-8799-39bd184d8de8",
    "group_id": "8c7e55e4-7602-4a39-8ed1-6286d20bd6ff"
}

### Remove Admin
PATCH {{host}}/admin/removeAdmin
Content-Type: application/json
Authorization: {{idToken}}

{
    "target_id": "4f98abae-2d0a-4e6b-8799-39bd184d8de8",
    "group_id": "8c7e55e4-7602-4a39-8ed1-6286d20bd6ff"
}

### Kick user
PATCH {{host}}/admin/kickUser
Content-Type: application/json
Authorization: {{idToken}}

{
    "user_id": "020496fe-a9cc-4b02-b02b-9502ff1c747b",
    "group_id": "8c7e55e4-7602-4a39-8ed1-6286d20bd6ff"
}

### Ban user
PATCH {{host}}/admin/banUser
Content-Type: application/json
Authorization: {{idToken}}

{
    "target_id": "4f98abae-2d0a-4e6b-8799-39bd184d8de8",
    "group_id": "7783b2b1-3a83-4534-9954-79bed3147ddf"
}

### Refresh user
GET {{host}}/auth/refreshToken
Content-Type: application/json
Authorization: {{idToken}}




