@host = http://localhost:3000

@contentType = application/json

@idToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BpY2VzcXVhZC1mZDMyYSIsImF1ZCI6InNwaWNlc3F1YWQtZmQzMmEiLCJhdXRoX3RpbWUiOjE2ODg2NzcyMDQsInVzZXJfaWQiOiJIZXN5TEVFaTBCTzk1bFBaSzhaaGJ3R0hLTUsyIiwic3ViIjoiSGVzeUxFRWkwQk85NWxQWks4Wmhid0dIS01LMiIsImlhdCI6MTY4ODY3NzIwNCwiZXhwIjoxNjg4NjgwODA0LCJlbWFpbCI6Imx1a2Fzc3MyMzJjaHdzc2FyekBtYWlsYm94Lm9yZyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJsdWthc3NzMjMyY2h3c3NhcnpAbWFpbGJveC5vcmciXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.CQpO-tFHOS7boTKGcgAtTttmGqHi19OM91sLI2yIw_hxa6gALswQboigCaOqeKs2CgpViu4jDgxEFqEyjLdZMkCvh6oidi7l4IFefaFPPnS36HiID57MnUSAww1Qwku0d_9ntX5jP9EVL_mdlyQx8hkuUWLa4r7psgArbniG1Vul9h3SpR8GOu1EKqjAodE8bUNpPlL0x8VE3cNHW5l-jUPLMtmF1VIN5qTgm5bcIhifIpVxwMpx0r4_OlXBDa4g8M-FWYFl60-FmBtztyWfDdbD9wFz-5Dtw5Hd2BJ2G6aUGQiNFe1vHHdER_MmoHvsADQgN3DTuP_UtVRSnEQ2HQ
@refreshToken = APZUo0SDbxrtKbrOhZF_3KKlBy2kwnE9-kHgTNDNstaXpJP91UDiEOKji84uNtuuYouY4l1E5Yb4Dzgr5Hs88G-QluXFMOvO0wjHzYJY0WSDu_e7LgyF3hT8NOIi2gv9ME5XJXxKqPdr2ZvQFsscQjn0KL2FVx8HodqB574CpDw0suisbj_ZGxoHvVMj5ToDBkLThKzqNROfD-y9ct9K4rIhva_TMcbHQg

@user_name = "Lukas"
@email = "lukasss232chwssarz@mailbox.org"
@password = "12345678"

@groupId = 513a9ef2-3479-46a0-bc22-e6790c3a6283


##### API-Requests


#### AuthentificationController

### Test a not existing route
GET {{host}}/unknown
Content-Type: {{contentType}}

### Register new user
POST {{host}}/auth/register
Content-Type: {{contentType}}

{
    "userName": {{user_name}},
    "email": {{email}},
    "password": {{password}}
}

### Login user
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": {{email}},
    "password": {{password}}
}

### Reset password
POST {{host}}/auth/resetPassword
Content-Type: {{contentType}}

    {
        "email": "lukasschwarz@mailbox.org"
    }

### Refresh token
GET {{host}}/auth/refreshToken
Content-Type: {{contentType}}

    {
        "refreshToken": "APZUo0SDbxrtKbrOhZF_3KKlBy2kwnE9-kHgTNDNstaXpJP91UDiEOKji84uNtuuYouY4l1E5Yb4Dzgr5Hs88G-QluXFMOvO0wjHzYJY0WSDu_e7LgyF3hT8NOIi2gv9ME5XJXxKqPdr2ZvQFsscQjn0KL2FVx8HodqB574CpDw0suisbj_ZGxoHvVMj5ToDBkLThKzqNROfD-y9ct9K4rIhva_TMcbHQg"
    }

### Get user by token
GET {{host}}/auth/user
Content-Type: {{contentType}}
    
    {
        "idToken": {{idToken}}
    }



#### GroupController

### Create Group
POST {{host}}/group
Content-Type: {{contentType}}
Authorization: {{idToken}}

    {
        "groupName": "Trap House Kitchen"
    }

### Delete Group
DELETE {{host}}/group/{{groupId}}
Content-Type: {{contentType}}
Authorization: {{idToken}}

### Patch Group
PATCH {{host}}/group/{{groupId}}
Content-Type: {{contentType}}
Authorization: {{idToken}}

{
    "group_id": "4506dff6-f758-4606-8eb9-a7e3e4b7d0ba",
    "name": "Almanküche"
}

### Join group
PATCH {{host}}/group/join
Content-Type: application/json
Authorization: {{idToken}}

{
    "group_id": "7783b2b1-3a83-4534-9954-79bed3147ddf"
}

### Get Groups
GET {{host}}/group
Content-Type: application/json
Authorization: {{idToken}}

### Create recipe
POST {{host}}/recipe
Content-Type: {{contentType}}
Authorization: {{idToken}}

    {
        "title": "Test recipe",
        "image": "22",
        "duration": "30",
        "difficulty": "easy",
        "ingredients": [
            {
                "name": "Tomato",
                "iconName": "08b685d4-f076-4636-ac85-50225468f38c",
                "amount": "2",
                "unit": "pieces"
            },
            {
                "name": "Salt",
                "iconName": "08b685d4-f076-4636-ac85-50225468f38c",
                "amount": "1",
                "unit": "teaspoon"
            }
        ],
        "instructions": "Lorem impsum dolor sit amet",
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "isKosher": false,
        "isHalal": false,
        "isPrivate": false,
        "defaultPortions": "2"

    }

### Delete recipe
DELETE {{host}}/recipe/5ad5693e-430b-463a-976d-c3cde4c865ee
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "7256d142-e775-4297-bcaa-981ba1a0ff47"
}

### Get recipe
GET {{host}}/recipe/29026783-e796-49b8-98b6-d6f198b453f0
Content-Type: application/json
Authorization: {{idToken}}


### Update recipe
Patch {{host}}/recipe/5ad5693e-430b-463a-976d-c3cde4c865ee
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "51f5ce1c-a224-48ba-b643-bd72d965aac9",
    "title": "A updated recipe",
    "image": "21",
    "duration": "40",
    "difficulty": "medium",
    "ingredients": [
        {
            "name": "Tomato",
            "icon_name": "ds",
            "amount": "2",
            "unit": "pieces"
        },
        {
            "name": "Salt",
            "icon_name": "fe",
            "amount": "1",
            "unit": "teaspoon"
        }
    ],
    "instructions": "Lorem impsum dolor sit amet",
    "is_vegetarian": true,
    "is_vegan": false,
    "is_gluten_free": false,
    "is_kosher": false,
    "is_halal": false,
    "is_private": false,
    "default_portions": "2"

}

### Delete Recipe
DELETE {{host}}/recipe/5ad5693e-430b-463a-976d-c3cde4c865ee
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "7256d142-e775-4297-bcaa-981ba1a0ff47"
}
### Set recipe as favorite
PATCH {{host}}/recipe/setFavorite/51f5ce1c-a224-48ba-b643-bd72d965aac9
Content-Type: application/json
Authorization: {{idToken}}

{
    "is_favorite": false
}



### Get Recipes
GET {{host}}/recipe/4f98abae-2d0a-4e6b-8799-39bd184d8de8
Content-Type: application/json
Authorization: {{idToken}}

### Create recipe
POST {{host}}/recipe
Content-Type: application/json
Authorization: {{idToken}}

{
    "title": "Fils de pute",
    "image": "22",
    "duration": "30",
    "difficulty": "easy",
    "ingredients": [
        {
            "name": "Tomato",
            "icon_name": "08b685d4-f076-4636-ac85-50225468f38c",
            "amount": "2",
            "unit": "pieces"
        },
        {
            "name": "Salt",
            "icon_name": "08b685d4-f076-4636-ac85-50225468f38c",
            "amount": "1",
            "unit": "teaspoon"
        }
    ],
    "instructions": "8==D",
    "is_vegetarian": true,
    "is_vegan": false,
    "is_gluten_free": false,
    "is_kosher": false,
    "is_halal": false,
    "is_private": false,
    "default_portions": "2"

}

### Delete recipe
DELETE {{host}}/recipe/a23ae456-8d9a-4748-b6fd-2acd621eaa89
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "7eda6c37-c963-40a9-81c2-72b1382972b8"
}

### Get recipe
GET {{host}}/recipe/29026783-e796-49b8-98b6-d6f198b453f0
Content-Type: application/json
Authorization: {{idToken}}


### Update recipe
Patch {{host}}/recipe/5ad5693e-430b-463a-976d-c3cde4c865ee
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "51f5ce1c-a224-48ba-b643-bd72d965aac9",
    "title": "A updated recipe",
    "image": "21",
    "duration": "40",
    "difficulty": "medium",
    "ingredients": [
        {
            "name": "Tomato",
            "icon_name": "08b685d4-f076-4636-ac85-50225468f38c",
            "amount": "2",
            "unit": "pieces"
        },
        {
            "name": "Salt",
            "icon_name": "08b685d4-f076-4636-ac85-50225468f38c",
            "amount": "1",
            "unit": "teaspoon"
        }
    ],
    "instructions": "Lorem impsum dolor sit amet",
    "is_vegetarian": true,
    "is_vegan": false,
    "is_gluten_free": false,
    "is_kosher": false,
    "is_halal": false,
    "is_private": false,
    "default_portions": "2"

}

### Set recipe as favorite
PATCH {{host}}/recipe/setFavorite/51f5ce1c-a224-48ba-b643-bd72d965aac9
Content-Type: application/json
Authorization: {{idToken}}

{
    "is_favorite": false
}

### Censor recipe
PATCH {{host}}/admin/setCensored
Content-Type: application/json
Authorization: {{idToken}}

{
    "recipe_id": "d955d656-eed1-49f0-a5e9-9d1fb351023a",
    "group_id": "0913092b-efda-493f-8351-74e06d4a28d3"
}

### Make Admin
PATCH {{host}}/admin/makeAdmin
Content-Type: application/json
Authorization: {{idToken}}

{
    "target_id": "4f98abae-2d0a-4e6b-8799-39bd184d8de8",
    "group_id": "8c7e55e4-7602-4a39-8ed1-6286d20bd6ff"
}

### Remove Admin
PATCH {{host}}/admin/removeAdmin
Content-Type: application/json
Authorization: {{idToken}}

{
    "target_id": "4f98abae-2d0a-4e6b-8799-39bd184d8de8",
    "group_id": "8c7e55e4-7602-4a39-8ed1-6286d20bd6ff"
}

### Kick user
PATCH {{host}}/admin/kickUser
Content-Type: application/json
Authorization: {{idToken}}

{
    "user_id": "020496fe-a9cc-4b02-b02b-9502ff1c747b",
    "group_id": "8c7e55e4-7602-4a39-8ed1-6286d20bd6ff"
}

### Ban user
PATCH {{host}}/admin/banUser
Content-Type: application/json
Authorization: {{idToken}}

{
    "target_id": "4f98abae-2d0a-4e6b-8799-39bd184d8de8",
    "group_id": "7783b2b1-3a83-4534-9954-79bed3147ddf"
}

### Refresh user
GET {{host}}/auth/refreshToken
Content-Type: application/json
Authorization: {{idToken}}