name: Release Entwurfsheft PDF 
on:
  push:
    branches:
    - main

jobs:
  build-latex:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: entwurfsheft/entwurfsheft.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Entwurfsheft
          files: ./entwurfsheft/entwurfsheft.pdf
