name: Release Pflichtenheft PDF 
on:
  push:
    branches:
    - main

jobs:
  build-latex:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          post_compile: "makeglossaries pflichtenheft.glo"
          work_in_root_file_dir: true
          root_file: pflichtenheft/pflichtenheft.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Pflichtenheft
          files: ./pflichtenheft/pflichtenheft.pdf
