name: Release Pflichtenheft PDF 
on:
  push:
    branches:
    - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: pflichtenheft/pflichtenheft.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: pflichtenheft/pflichtenheft.pdf
      
